<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>4. The Incumbency Advantage | Election Prediction Blog</title>
    <link rel="stylesheet" href="/election-blog/css/style.css" />
    <link rel="stylesheet" href="/election-blog/css/fonts.css" />
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/election-blog/">Home</a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title"><ol start="4">
<li>The Incumbency Advantage</li>
</ol>
</span></h1>
<h2 class="author">Mena Solomon</h2>
<h2 class="date">2024/09/27</h2>
</div>

<main>
<h2 id="what-is-the-advantage-of-incumbency-in-presidential-elections">What is the advantage of incumbency in presidential elections?</h2>
<p><strong>There have been 18 presidential elections since World War II, eleven of which had at least one incumbent president running, seven of whom won re-election.</strong> Indeed, while an incumbent president has won re-election in 33% of the elections post WWII, the incumbent party has won over 44% of such presidential elections. These results point out a reality within U.S. politics: that incumbency is a major advantage for both politicians and parties within the context of a general election for President.</p>
<p><strong>How many incumbent presidents have been re-elected since WWII?</strong></p>
<table>
  <thead>
      <tr>
          <th style="text-align: left">Was the incumbent president re-elected</th>
          <th style="text-align: right">Count</th>
          <th style="text-align: right">Percent</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td style="text-align: left">FALSE</td>
          <td style="text-align: right">12</td>
          <td style="text-align: right">66.67</td>
      </tr>
      <tr>
          <td style="text-align: left">TRUE</td>
          <td style="text-align: right">6</td>
          <td style="text-align: right">33.33</td>
      </tr>
  </tbody>
</table>
<p><strong>How many incumbent parties have been re-elected since WWII?</strong></p>
<table>
  <thead>
      <tr>
          <th style="text-align: left">Was the incumbent party re-elected</th>
          <th style="text-align: right">Count</th>
          <th style="text-align: right">Percent</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td style="text-align: left">FALSE</td>
          <td style="text-align: right">10</td>
          <td style="text-align: right">55.56</td>
      </tr>
      <tr>
          <td style="text-align: left">TRUE</td>
          <td style="text-align: right">8</td>
          <td style="text-align: right">44.44</td>
      </tr>
  </tbody>
</table>
<h2 id="historically-why-do-incumbents-have-this-advantage">Historically, why do incumbents have this advantage?</h2>
<p>As seen above, incumbency presents a huge advantage for both presidents and their parties within presidential elections. Scholar Alfred Cuzán describes this effect as one of the five laws of politics — <strong>the law of incumbent advantage</strong>. Cuzán&rsquo;s second of the five laws, however, paints a more complicated picture of this effect. <strong>The law of shrinking support</strong> asserts that despite the incumbent advantage in the presidential election, all but one incumbent’s party has lost vote share in midterm house election since WWII.<a href="https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/abs/five-laws-of-politics/693D6F468706FB21FD043397D88FC0C3?utm_campaign=shareaholic&amp;utm_medium=copy_link&amp;utm_source=bookmark">(Cuzán, 2015)</a> This is often due to a phenomenon called mean reversion wherein parties who overperform and gain marginal seats in one election, will typically revert to the mean in the next election, returning to their historical average number of seats.</p>
<p>The law of incumbent advantage is, thus, specific to the office of the president. First and foremost, politicians are able to shape public opinion because of high esteem and recognition. Incumbents are able to begin their campaigns for re-election from the second that they arrive in the oval office, giving them a jumpstart on the race. Furthermore, according to Kriner and Reeves, Presidents can use the distribution of federal funds to garner electoral support.<a href="https://hollis.harvard.edu/permalink/f/1mdq5o5/TN_cdi_proquest_journals_1018073231">(Kriner and Reeves, 2012)</a> One aspect of this spending, called pork barrel spending, targets certain politicians to help with their re-election campaigns.</p>
<img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-4-1.png" width="1536" />
<p><strong>As seen above, federal grant spending in swing states is significantly higher than in non-swing states. Furthermore, this spending increases significantly in an election year.</strong> Finally, this effect applies both to incumbents and their successors. To analyze the relationship between incumbent vote share and federal grant spending at the county level, a bivariate regression was run which resulted in an r-squared value of 0.4, meaning this model can explain 40% of the variance in incumbent vote share. <em>The model asserts that both grant spending and the competitiveness of states influence incumbent vote share, a finding which is statistically significant at the 0.001 level.</em> The model also indicates that the coefficients for years 1996, 2004, and 2008 are significantly larger than the base year, suggesting important temporal effects during these elections. When analyzing a separate bivariate regression model which uses grant data at the state level, these temporal effects persist in 1996 and 2004, indicating significant pork barrel spending by Bush and Clinton to support their re-election campaigns.</p>
<h2 id="can-incumbency-build-a-predictive-model">Can incumbency build a predictive model?</h2>
<p>While federal grant data for 2024 is not yet available, incumbency can be easily incorporated into predictive models by incorporating whether or not a candidate is an incumbent as well as the president&rsquo;s approval rating. One such model which incorporates both of these statistics, as well as quarter 2 GDP growth, was made by the political scientist Alan Abramowitz. <strong>Abramowitz&rsquo;s Time for Change model had a true out-of-sample PV prediction error of 1.7% between 1992 and 2016.</strong></p>
<table>
  <thead>
      <tr>
          <th style="text-align: left">Prediction Models</th>
          <th style="text-align: right">Predicted 2024 Democratic Voteshare</th>
          <th style="text-align: right">Lower Bound (95% PI)</th>
          <th style="text-align: right">Upper Bound (95% PI)</th>
      </tr>
  </thead>
  <tbody>
      <tr>
          <td style="text-align: left">Time for Change Model (2016)</td>
          <td style="text-align: right">48.92874</td>
          <td style="text-align: right">43.09807</td>
          <td style="text-align: right">54.75942</td>
      </tr>
      <tr>
          <td style="text-align: left">Simplified Time for Change Model (2020)</td>
          <td style="text-align: right">47.39554</td>
          <td style="text-align: right">40.52536</td>
          <td style="text-align: right">54.26573</td>
      </tr>
  </tbody>
</table>
<p>The table above uses both the 2016 model as well as the simplified 2020 model to predict the results of the 2024 election. The 2016 model includes incumbency advantage (as determined by incumbency status as well as June approval ratings) as well as GDP growth quarterly. <a href="https://menemshasolomon.github.io/election-blog/post/2024-09-14-2-the-importance-of-the-economy/">To better understand the inclusion of economic fundamentals, refer to blog post two.</a> <strong>This model estimates a 48.93% two-party popular vote share for Vice President Harris.</strong> To make this prediction, a prediction interval of 95% was used, meaning that there is only a 5% chance the real election outcome does not fall within the upper and lower bounds noted above. The 2020 time for change model only utilizes june approval ratings as a predictor, <strong>estimating a 47.4% two-party popular vote share for Vice President Harris.</strong></p>
<p><strong>These two predictions differ significantly than those mode in previous weeks, primarily because they rely on Biden&rsquo;s incumbency status and approval ratings despite the reality that Biden is no longer the democratic candidate for president.</strong> Indeed, in June (the month of the first presidential debate) Biden&rsquo;s approval rating was -22, which is certainly not the case for his younger successor Kamala Harris. The complicated narrative of this election makes it difficult to incorporate incumbency advantage into a prediction model.</p>
<h2 id="using-this-model-can-we-predit-the-results-of-the-2024-presidential-election">Using this model, can we predit the results of the 2024 presidential election?</h2>
<pre><code>## # A tibble: 5 × 2
##    year mean_match_rate
##   &lt;dbl&gt;           &lt;dbl&gt;
## 1  2004           0.647
## 2  2008           0.608
## 3  2012           0.765
## 4  2016           0.804
## 5  2020           0.824
</code></pre>
<p><img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-6-2.png" width="672" /><img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-6-3.png" width="672" /><img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-6-4.png" width="672" /><img src="https://menemshasolomon.github.io/election-blog/post/2024-09-27-4-the-incumbency-advantage/index_files/figure-html/unnamed-chunk-6-5.png" width="672" /></p>
<pre><code>## 
##  0  1 
##  9 42
</code></pre>
<pre><code>## [1] &quot;Florida&quot;        &quot;Georgia&quot;        &quot;Iowa&quot;           &quot;Minnesota&quot;     
## [5] &quot;New Hampshire&quot;  &quot;New Mexico&quot;     &quot;North Carolina&quot; &quot;Ohio&quot;          
## [9] &quot;Texas&quot;
</code></pre>
<pre><code>## # A tibble: 9 × 5
##   state          cook_rating region         sabato_rating rating_match
##   &lt;chr&gt;                &lt;dbl&gt; &lt;chr&gt;                  &lt;dbl&gt;        &lt;dbl&gt;
## 1 Florida                  4 florida                    5            0
## 2 Georgia                  4 georgia                    3            0
## 3 Iowa                     4 iowa                       5            0
## 4 Minnesota                3 minnesota                  2            0
## 5 New Hampshire            3 new hampshire              2            0
## 6 New Mexico               1 new mexico                 2            0
## 7 North Carolina           4 north carolina             3            0
## 8 Ohio                     4 ohio                       5            0
## 9 Texas                    4 texas                      5            0
</code></pre>
<pre><code>##   cook_correct sabato_correct 
##      0.8823529      0.9803922
</code></pre>
<pre><code>## [1] &quot;Florida&quot;        &quot;Georgia&quot;        &quot;Iowa&quot;           &quot;North Carolina&quot;
## [5] &quot;Ohio&quot;           &quot;Texas&quot;
</code></pre>
<pre><code>## [1] &quot;North Carolina&quot;
</code></pre>
<pre><code>## # A tibble: 7 × 1
##   state         
##   &lt;chr&gt;         
## 1 Arizona       
## 2 Georgia       
## 3 Michigan      
## 4 Nevada        
## 5 North Carolina
## 6 Pennsylvania  
## 7 Wisconsin
</code></pre>
<pre><code>##   cook_correct sabato_correct 
##      0.8549020      0.9137255
</code></pre>
<pre><code>## # A tibble: 5 × 3
##    year mean_cook_correct mean_sabato_correct
##   &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;
## 1  2004             0.824               0.961
## 2  2008             0.804               0.784
## 3  2012             0.863               0.961
## 4  2016             0.902               0.882
## 5  2020             0.882               0.980
</code></pre>

</main>

  <footer>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
<script src="//cdn.jsdelivr.net/combine/npm/katex/dist/katex.min.js,npm/katex/dist/contrib/auto-render.min.js,npm/@xiee/utils/js/render-katex.js" defer></script>

<script src="//cdn.jsdelivr.net/npm/@xiee/utils/js/center-img.min.js" defer></script>

  
  <hr/>
  Mena Solomon | <a href="https://github.com/menemshasolomon/election-blog">Github</a> | 2024
  
  </footer>
  </body>
</html>

